

 
import java.util.List;
/*
 * DO NOT EDIT THIS FILE
 */
public interface IPrinter { 
    /*
      	remove from the list of printers "a" all printers which has price less than or equals to given price.   
     */
    
    void f1(List<Printer> a, double price);
   
    /*
       count and return numbers of printers which are in the list "a" and 
        has name contains given name.
    */
    public int f2(List<Printer> a, String name);
}
